title: Ícaro Niz
description: Senior Frontend Engineer and Technical Lead
url: "https://www.icaroniz.com"
baseurl: ""

# Build
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

# Sass
sass:
  style: compressed